spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      username: technologyos
      password: YXNhbGF6YXJqQGdtYWlsLmNvbToqR
      database: my_db
      authentication-database: admin
